name: Release Please
on:
  push:
    branches:
      - 'main'
      - 'releases/**'

permissions:
  contents: write
  pull-requests: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-please:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: maven
          target-branch: ${{ github.ref_name }}
  build-and-push:
    name: Build image
    runs-on: ubuntu-latest
    needs: release-please
    # if: ${{ needs.release_please.outputs.releases_created == 'true' }}
    outputs:
      tag-name: ${{ needs.release_please.outputs.tag_name }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
      - name: Check tag-name output
        run: |
          echo ${{ needs.release_please.outputs.tag_name }}
      - name: Check meta tags output
        run: |
          echo ${{ steps.meta.outputs.tags }}
#      - name: Build and push image
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: true
#          tags: ${{ needs.release_please.outputs.tag_name }}
#          labels: ${{ steps.meta.outputs.labels }}
