name: Release Test

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push"]
    types:
      - completed
jobs:
  build:
    name: Release Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cschleiden/replace-tokens@v1
        name: Replace tokens in manifest
        with:
          files: '${{ github.workspace }}/k8s/manifest.yml'
        env:
          Namespace: remote-falcon-test
          Application: remote-falcon-control-panel
          Env: test
          Replicas: 1
          Image: whitesoup12/remote-falcon-control-panel
          Tag: ${{ github.sha }}
          Requests.Memory: 500Mi
          Requests.CPU: 250m
          Limits.Memory: 750Mi
          Limits.CPU: 500m
          DockerHubSecret: docker-hub
          Host: remotefalcon.dev
          
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 4fee5fb4-939b-4d7a-8eb0-1b31115a74dc

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Kubectl apply
        run: kubectl apply -f ${{ github.workspace }}/k8s/manifest.yml
